default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  min_messages: warning

development:
  <<: *default
  database: projetcname_development
  username: username
  password: password

test:
  <<: *default
  database: projetcname_test
  username: username
  password: password